# Generated by Django 2.2 on 2020-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(max_length=10)),
                ('customer_id', models.IntegerField(max_length=10)),
                ('review_comment', models.TextField(max_length=500)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
