# Generated by Django 2.2 on 2020-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereviews',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicereviews',
            name='service_id',
            field=models.IntegerField(),
        ),
    ]
