# Generated by Django 2.2 on 2020-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200125_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereviews',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
