# Generated by Django 2.2 on 2020-01-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_servicereviews_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicereviews',
            old_name='service_id',
            new_name='service',
        ),
    ]
