# Generated by Django 2.2 on 2019-12-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, unique=True)),
                ('url_key', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='servicecategory')),
            ],
            options={
                'verbose_name': 'servicecategory',
                'verbose_name_plural': 'servicecategories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, unique=True)),
                ('url_key', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='serviceproduct')),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('popularity', models.IntegerField(default=0)),
                ('servicecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecatalog.ServiceCategory')),
            ],
            options={
                'verbose_name': 'serviceproduct',
                'verbose_name_plural': 'serviceproducts',
                'ordering': ('product_name',),
            },
        ),
    ]
