# Generated by Django 2.2 on 2019-12-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('category_name',), 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='serviceproduct',
            options={'ordering': ('product_name',), 'verbose_name': 'Service Product', 'verbose_name_plural': 'Service Products'},
        ),
    ]
