# Generated by Django 2.2 on 2019-12-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicecatalog', '0002_auto_20191228_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(blank=True, max_length=300)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Quote',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Quote')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecatalog.ServiceProduct')),
            ],
            options={
                'db_table': 'QuoteItem',
            },
        ),
    ]
