# Generated by Django 2.2 on 2019-12-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteitem',
            old_name='cart',
            new_name='quote',
        ),
    ]
