# Generated by Django 2.2 on 2020-01-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
